config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
  end
  resources :likes
  devise_for :users
  get '/messages', to: 'message#index'
  get '/profile', to: 'profile#index'
  get '/post-list', to: 'post_list#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :likes, as: :likeable, class_name: Like.name
end

app/models/follow.rb
class Follow < ApplicationRecord
  #the giving the follow
  belongs_to :follower, foreign_key: :follower_id, class_name: "User"

  #the user being followed
  belongs_to :followed_user, foreign_key: :followed_user_id, class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likeable, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, as: :likeable, class_name: Like.name
  has_many :comments, as: :commentable
  has_one_attached :image
  scope :ordered, -> {order(id: :desc)}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :avatar
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment= @post.comments.create(comment_params)
  end

  private
  def comment_params
    params.require(:comment).permit(:body).merge({user: current_user})
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.new(like_params)
    if @like.save
      render html: "<h1>logrado</h1>"
    else
      render html: "no logrado"
    end
  end

  private
    def like_params
      params.permit(:likeable_type, :likeable_id ).merge({user: current_user})
    end

end

app/controllers/message_controller.rb
class MessageController < ApplicationController
  before_action :authenticate_user!
  layout "navbar"
end

app/controllers/post_list_controller.rb
class PostListController < ApplicationController
  before_action :authenticate_user!
  layout "navbar"
  def index
    @post = Post.new(post_parameters)
  end

  private


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  layout "navbar"

  # GET /posts or /posts.json
  def index
    @posts = Post.ordered
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.required(:post).permit(:body, :image).merge({ user: current_user })
    end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :authenticate_user!
  layout "navbar"
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/conversation_helper.rb
module ConversationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/navbar_helper.rb
module NavbarHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/post_list_helper.rb
module PostListHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/message/index.html.slim
.bg-gray-50.w-screen.h-screen.sm:p-5
  .bg-white.border.border-gray-200.rounded.flex.h-full
    .w-full.sm:w-1/2.md:w-1/3.lg:w-1/4.h-full
      .border-b.border-gray-200.p-3.relative
        button.flex.items-center.mx-auto.select-none.font-semibold.focus:outline-none
          |  neysidev
          svg.ml-1.transform.rotate-180.translate-y-0.5[height="20" viewbox="0 0 48 48" width="20"]
            path[d="M40 33.5c-.4 0-.8-.1-1.1-.4L24 18.1l-14.9 15c-.6.6-1.5.6-2.1 0s-.6-1.5 0-2.1l16-16c.6-.6 1.5-.6 2.1 0l16 16c.6.6.6 1.5 0 2.1-.3.3-.7.4-1.1.4z"]
        button.absolute.right-3.top-1/2.transform.-translate-y-1/2.focus:outline-none
          svg[height="20" viewbox="0 0 44 44" width="20"]
            path[d="M33.7 44.12H8.5a8.41 8.41 0 01-8.5-8.5v-25.2a8.41 8.41 0 018.5-8.5H23a1.5 1.5 0 010 3H8.5a5.45 5.45 0 00-5.5 5.5v25.2a5.45 5.45 0 005.5 5.5h25.2a5.45 5.45 0 005.5-5.5v-14.5a1.5 1.5 0 013 0v14.5a8.41 8.41 0 01-8.5 8.5z"]
            path[d="M17.5 34.82h-6.7a1.5 1.5 0 01-1.5-1.5v-6.7a1.5 1.5 0 01.44-1.06L34.1 1.26a4.45 4.45 0 016.22 0l2.5 2.5a4.45 4.45 0 010 6.22l-24.3 24.4a1.5 1.5 0 01-1.02.44zm-5.2-3h4.58l23.86-24a1.45 1.45 0 000-2l-2.5-2.5a1.45 1.45 0 00-2 0l-24 23.86z"]
            path[d="M38.2 14.02a1.51 1.51 0 01-1.1-.44l-6.56-6.56a1.5 1.5 0 012.12-2.12l6.6 6.6a1.49 1.49 0 010 2.12 1.51 1.51 0 01-1.06.4z"]
      .flex.items-center.justify-between.text-sm.border-b.border-gray-200
        div
          button.py-3.w-20.uppercase.font-semibold.select-none.h-full.focus:outline-none.border-b.border-black
            |  Primary
          button.py-3.w-20.uppercase.text-gray-400.select-none.h-full.focus:outline-none.border-b.border-transparent
            |  General
        button.p-3.font-semibold.text-blue-500.select-none.h-full.focus:outline-none.border-b.border-transparent
          |  1 Request
      ul.py-1.overflow-auto
        li
          button.flex.items-center.w-full.px-4.py-2.select-none.hover:bg-gray-100.focus:outline-none
            img.w-12.mr-3.rounded-full.border[src="https://i.ibb.co/0ZDqmDs/142030673-447983159572512-6561194794076636819-n.jpg" alt="Junior Coders"]
            .transform.translate-y-0.5.text-left
              h3.leading-4
                | junior.coders
              span.text-xs.text-gray-500
                | Active 20s ago
        li
          button.flex.items-center.w-full.px-4.py-2.select-none.hover:bg-gray-100.focus:outline-none
            img.w-12.mr-3.rounded-full.border[src="https://i.ibb.co/n8D3NYv/107410209-890400198133639-1048997058040173171-n.jpg" alt="Tabaghe 16"]
            .transform.translate-y-0.5.text-left
              h3.leading-4
                | tabaghe16
              span.text-xs.text-gray-500
                | Active 6h ago
        li
          button.flex.items-center.w-full.px-4.py-2.select-none.hover:bg-gray-100.focus:outline-none
            img.w-12.mr-3.rounded-full.border[src="https://i.ibb.co/bPb39qC/146062600-790305448495619-4399071814928120955-n.jpg" alt="MegaCoders"]
            .transform.translate-y-0.5.text-left
              h3.leading-4
                | megacoders
              span.text-xs.text-gray-500
                | Active 15min ago
        li
          button.flex.items-center.w-full.px-4.py-2.select-none.hover:bg-gray-100.focus:outline-none
            img.w-12.mr-3.rounded-full.border[src="https://i.ibb.co/Y7H2b8s/83915635-1271088396614888-3530566050498215936-n.jpg" alt="Graphhit"]
            .transform.translate-y-0.5.text-left
              h3.leading-4
                | graphhit.ir
              span.text-xs.text-gray-500
                | Active 8h ago
        li
          button.flex.items-center.w-full.px-4.py-2.select-none.hover:bg-gray-100.focus:outline-none
            img.w-12.mr-3.rounded-full.border[src="https://i.ibb.co/5RTNZzq/120597858-373955600298386-171038155143224317-n.jpg" alt="Dex Design"]
            .transform.translate-y-0.5.text-left
              h3.leading-4
                | dex.design
              span.text-xs.text-gray-500
                | Active 30min ago
        li
          button.flex.items-center.w-full.px-4.py-2.select-none.hover:bg-gray-100.focus:outline-none
            img.w-12.mr-3.rounded-full.border[src="https://i.ibb.co/PgxfpHJ/135397005-118438206790158-4813733027837640666-n.jpg" alt="Khoshbakhti"]
            .transform.translate-y-0.5.text-left
              h3.leading-4
                | khoshbakhti_official
              span.text-xs.text-gray-500
                | Active Yesterday
    .hidden.sm:w-1/2.md:w-2/3.lg:w-3/4.border-l.border-gray-200.sm:flex.items-center.justify-center.text-center
      .space-y-5
        .border.border-black.rounded-full.inline-flex.p-5.items-center.justify-center
          svg.transform.translate-y-1[height="52" viewbox="0 0 48 48" width="52"]
            path[d="M47.8 3.8c-.3-.5-.8-.8-1.3-.8h-45C.9 3.1.3 3.5.1 4S0 5.2.4 5.7l13.2 13c.5.4 1.1.6 1.7.3l16.6-8c.7-.3 1.6-.1 2 .5.4.7.2 1.6-.5 2l-15.6 9.9c-.5.3-.8 1-.7 1.6l4.6 19c.1.6.6 1 1.2 1.1h.2c.5 0 1-.3 1.3-.7l23.2-39c.5-.5.5-1.1.2-1.6z"]
        .space-y-0.5
          h1.font-semibold.text-xl
            | Your Messages
          p.text-gray-600.min-w-46
            | Send private photos and messages to a friend or group
        button.bg-blue-500.py-1.px-3.rounded.text-white.select-none.focus:outline-none
          | Send Message

app/views/post_list/_new_post.html.slim
=form_with(model:@post) do |f|
  -f.options[:html][:class]= "bg-white.shadow.rounded-lg.mb-6.p-4.w-full md:w-3/4"
  textarea.focus:outline-none.w-full.rounded-lg.p-2.text-sm.bg-gray-100.border.border-transparent.appearance-none.rounded-tg.placeholder-gray-400 name="message" placeholder=("Type something...")
  footer.flex.justify-between.mt-2
    .flex.gap-2
      span.flex.items-center.transition.ease-out.duration-300.hover:bg-blue-500.hover:text-white.bg-blue-100.w-8.h-8.px-2.rounded-full.text-blue-400.cursor-pointer
        svg.css-i6dzq1 fill="none" height="24" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox=("0 0 24 24") width="24"
          rect height="18" rx="2" ry="2" width="18" x="3" y="3"
          circle cx="8.5" cy="8.5" r="1.5"
          polyline points=("21 15 16 10 5 21")
    button.flex.items-center.py-2.px-4.rounded-lg.text-sm.bg-blue-600.text-white.shadow-lg
      | Send
      svg.ml-1 fill="none" height="16" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox=("0 0 24 24") width="16"
        line x1="22" x2="11" y1="2" y2="13"
        polygon points=("22 2 15 22 11 13 2 9 22 2")

app/views/post_list/_post.html.slim
.feed-item.border.border-gray-400.rounded.bg-white
  .header.border-b.p-4.flex.justify-between.items-center
    .left.flex.flex-row.items-center
      .user-img.h-10.w-10.border.rounded-full.overflow-hidden.mr-4
        img._6q-tv alt=("nike's profile picture") data-testid="user-avatar" draggable="false" src="https://scontent-nrt1-1.cdninstagram.com/v/t51.2885-19/s150x150/20635165_1942203892713915_5464937638928580608_a.jpg?_nc_ht=scontent-nrt1-1.cdninstagram.com&_nc_ohc=JK-0WwYKXBgAX-mFP6I&oh=e0d86b1c4be3cea94e341f18e17905b3&oe=5F94C764" /
      .user-name-and-place.flex.flex-col
        span.text-sm.font-bold apple
        span.text-xs.font-light.text-gray-900 Chiapas, Mexico
    .right
      svg._8-yf5 aria-label=("More options") fill="#262626" height="16" viewbox=("0 0 48 48") width="16"
        circle clip-rule="evenodd" cx="8" cy="24" fill-rule="evenodd" r="4.5"
        circle clip-rule="evenodd" cx="24" cy="24" fill-rule="evenodd" r="4.5"
        circle clip-rule="evenodd" cx="40" cy="24" fill-rule="evenodd" r="4.5"
  .feed-img
    img alt="" src="https://images.unsplash.com/photo-1512054502232-10a0a035d672?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=80" /
  .card-footer.p-4
    .top
      .icons.flex.flex-row.justify-between.items-center
        .left.flex.flex-row
          .like.mr-4
            svg._8-yf5 aria-label="Like" fill="#262626" height="24" viewbox=("0 0 48 48") width="24"
              path d=("M34.6 6.1c5.7 0 10.4 5.2 10.4 11.5 0 6.8-5.9 11-11.5 16S25 41.3 24 41.9c-1.1-.7-4.7-4-9.5-8.3-5.7-5-11.5-9.2-11.5-16C3 11.3 7.7 6.1 13.4 6.1c4.2 0 6.5 2 8.1 4.3 1.9 2.6 2.2 3.9 2.5 3.9.3 0 .6-1.3 2.5-3.9 1.6-2.3 3.9-4.3 8.1-4.3m0-3c-4.5 0-7.9 1.8-10.6 5.6-2.7-3.7-6.1-5.5-10.6-5.5C6 3.1 0 9.6 0 17.6c0 7.3 5.4 12 10.6 16.5.6.5 1.3 1.1 1.9 1.7l2.3 2c4.4 3.9 6.6 5.9 7.6 6.5.5.3 1.1.5 1.6.5.6 0 1.1-.2 1.6-.5 1-.6 2.8-2.2 7.8-6.8l2-1.8c.7-.6 1.3-1.2 2-1.7C42.7 29.6 48 25 48 17.6c0-8-6-14.5-13.4-14.5z")

          =button_to "like", post_likes_path(@post), method: :post
          .comment.mr-4
            svg._8-yf5 aria-label="Comment" fill="#262626" height="24" viewbox=("0 0 48 48") width="24"
              path clip-rule="evenodd" d=("M47.5 46.1l-2.8-11c1.8-3.3 2.8-7.1 2.8-11.1C47.5 11 37 .5 24 .5S.5 11 .5 24 11 47.5 24 47.5c4 0 7.8-1 11.1-2.8l11 2.8c.8.2 1.6-.6 1.4-1.4zm-3-22.1c0 4-1 7-2.6 10-.2.4-.3.9-.2 1.4l2.1 8.4-8.3-2.1c-.5-.1-1-.1-1.4.2-1.8 1-5.2 2.6-10 2.6-11.4 0-20.6-9.2-20.6-20.5S12.7 3.5 24 3.5 44.5 12.7 44.5 24z") fill-rule="evenodd"
          .share
            svg._8-yf5 aria-label=("Share Post") fill="#262626" height="24" viewbox=("0 0 48 48") width="24"
              path d=("M47.8 3.8c-.3-.5-.8-.8-1.3-.8h-45C.9 3.1.3 3.5.1 4S0 5.2.4 5.7l15.9 15.6 5.5 22.6c.1.6.6 1 1.2 1.1h.2c.5 0 1-.3 1.3-.7l23.2-39c.4-.4.4-1 .1-1.5zM5.2 6.1h35.5L18 18.7 5.2 6.1zm18.7 33.6l-4.4-18.4L42.4 8.6 23.9 39.7z")
        .right
          .save
            svg._8-yf5 aria-label="Save" fill="#262626" height="24" viewbox=("0 0 48 48") width="24"
              path d=("M43.5 48c-.4 0-.8-.2-1.1-.4L24 29 5.6 47.6c-.4.4-1.1.6-1.6.3-.6-.2-1-.8-1-1.4v-45C3 .7 3.7 0 4.5 0h39c.8 0 1.5.7 1.5 1.5v45c0 .6-.4 1.2-.9 1.4-.2.1-.4.1-.6.1zM24 26c.8 0 1.6.3 2.2.9l15.8 16V3H6v39.9l15.8-16c.6-.6 1.4-.9 2.2-.9z")
      .likes.mt-1
        span.font-bold.text-sm
          | 122,780 likes
      .caption.text-sm.mt-3
        b apple
        | new Iphone release ✨
      .post-date.mt-1
        span.text-xs.text-gray-900
          | 1 minute ago
    .bottom.border-t.pt-3.mt-3
      .wrapper.flex
        input.text-sm.h-10.w-full.outline-none.focus:outline-none class="w-10/12" placeholder=("Add a comment") type="text" /
        button.text-blue-500.opacity-75.text-right.font-bold class="w-2/12"  post

app/views/post_list/index.html.slim
.page-content.pt-6.h-full
  .container.mx-auto.flex.h-full
    .left.pr-4 class="w-8/12"
      == render 'new_post'
      .feeds
        .feed-wrapper.mb-
          == render 'post'
    .right.h-screen.overflow-visible.h-full class="w-4/12"
      .first.fixed.pl-4.w-full style=("top:85px;  max-width: 293px;")
        .profile.flex.items-center.p-3.mb-4
          .avatar.rounded-full.overflow-hidden.mr-3
            img alt="" height="56px" src="https://scontent-ort2-1.cdninstagram.com/v/t51.2885-19/44884218_345707102882519_2446069589734326272_n.jpg?_nc_ht=scontent-ort2-1.cdninstagram.com&_nc_ohc=RLYRR3IenIMAX_WuH3u&oh=f63257aee4bcbf147d7a26c7da5b3467&oe=5F96310F" width="56px" /
          .user-name
            span.text-lg.font-semibold.text-gray-700 u__graphics
            span.text-sm.text-gray-600.block Ugraphics
        .suggestion-users
          .title.flex.w-full.justify-between.text-sm
            .left
              h1.font-bold Suggestions For You
            .right
              span See All
          .users-wrapper.mt-4.flex.w-full.justify-between.items-center
            .user-item.flex.flex-row.pl-2
              .user-img.h-10.w-10.border.rounded-full.overflow-hidden.mr-4
                img alt=("realdonaldtrump's profile picture") src="https://scontent-nrt1-1.cdninstagram.com/v/t51.2885-19/s150x150/23823676_515039535523575_7479748231031685120_n.jpg?_nc_ht=scontent-nrt1-1.cdninstagram.com&_nc_ohc=zLTqJ5i4bawAX9aEwSk&oh=3bd3cf886021fc3ad74a9258163f319b&oe=5F93487B" /
              .user-name.flex.flex-col
                span.text-sm.font-semibold realdonaldtrump
                span.text-xs.-mt-1.text-gray-700 populer
            a.follow.text-blue-600.text-sm.font-semibold href=""  follow
          .users-wrapper.mt-4.flex.w-full.justify-between.items-center
            .user-item.flex.flex-row.pl-2
              .user-img.h-10.w-10.border.rounded-full.overflow-hidden.mr-4
                img._6q-tv alt=("shinzoabe's profile picture") data-testid="user-avatar" draggable="false" src="https://scontent-nrt1-1.cdninstagram.com/v/t51.2885-19/s150x150/28765771_2034399086813186_5509661386784899072_n.jpg?_nc_ht=scontent-nrt1-1.cdninstagram.com&_nc_ohc=qheOj6mJM98AX83my9F&oh=8a8985205ad5a19ae0905a3c3a77906b&oe=5F93F87C" /
              .user-name.flex.flex-col
                span.text-sm.font-semibold shinzoabe
                span.text-xs.-mt-1.text-gray-700 populer
            a.follow.text-blue-600.text-sm.font-semibold href=""  follow
          .users-wrapper.mt-4.flex.w-full.justify-between.items-center
            .user-item.flex.flex-row.pl-2
              .user-img.h-10.w-10.border.rounded-full.overflow-hidden.mr-4
                img._6q-tv alt=("nike's profile picture") data-testid="user-avatar" draggable="false" src="https://scontent-nrt1-1.cdninstagram.com/v/t51.2885-19/s150x150/26155970_1584552474997482_4541081815552622592_n.jpg?_nc_ht=scontent-nrt1-1.cdninstagram.com&_nc_ohc=f5mhOmP7WT0AX9kw3Eh&oh=fd2a3ba71bee8608cda04d04196746b8&oe=5F94C3CE" /
              .user-name.flex.flex-col
                span.text-sm.font-semibold nike
                span.text-xs.-mt-1.text-gray-700 populer
            a.follow.text-blue-600.text-sm.font-semibold href=""  follow