config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
  end
  resources :likes
  devise_for :users
  get '/messages', to: 'message#index'
  get '/profile', to: 'profile#index'
  get '/post-list', to: 'post_list#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :likes, as: :likeable, class_name: Like.name
end

app/models/follow.rb
class Follow < ApplicationRecord
  #the giving the follow
  belongs_to :follower, foreign_key: :follower_id, class_name: "User"

  #the user being followed
  belongs_to :followed_user, foreign_key: :followed_user_id, class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likeable, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, as: :likeable, class_name: Like.name
  has_many :comments, as: :commentable
  has_one_attached :image
  scope :ordered, -> {order(id: :desc)}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :avatar])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment= @post.comments.create(comment_params)
  end

  private
  def comment_params
    params.require(:comment).permit(:body).merge({user: current_user})
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.new(like_params)
    if @like.save
      render html: "<h1>logrado</h1>"
    else
      render html: "no logrado"
    end
  end

  private
    def like_params
      params.permit(:likeable_type, :likeable_id ).merge({user: current_user})
    end

end

app/controllers/message_controller.rb
class MessageController < ApplicationController
  before_action :authenticate_user!
  layout "navbar"
end

app/controllers/post_list_controller.rb
class PostListController < ApplicationController
  before_action :authenticate_user!
  layout "navbar"
  def index
    @post = Post.new(post_parameters)
  end

  private


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  layout "navbar"

  # GET /posts or /posts.json
  def index
    @posts = Post.ordered
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.required(:post).permit(:body, :image).merge({ user: current_user })
    end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :authenticate_user!
  layout "navbar"
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/conversation_helper.rb
module ConversationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/navbar_helper.rb
module NavbarHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/post_list_helper.rb
module PostListHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/posts/_form.html.slim
= form_with(model: @post) do |form|
  - if @post.errors.any?
    div style="color: red"
      h2 = "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      ul
        - @post.errors.each do |error|
          li = error.full_message
  h1 create u post!!!
  =form.text_area :body
  br
  =form.file_field :image
  div
    = form.submit


.pt-10
  form.bg-white.shadow.rounded-lg.mb-6.p-4.w-full.md:w-3/4
    textarea.focus:outline-none.w-full.rounded-lg.p-2.text-sm.bg-gray-100.border.border-transparent.appearance-none.rounded-tg.placeholder-gray-400[name="message" placeholder="Type something..."]
    footer.flex.justify-between.mt-2
      .flex.gap-2
        span.flex.items-center.transition.ease-out.duration-300.hover:bg-blue-500.hover:text-white.bg-blue-100.w-8.h-8.px-2.rounded-full.text-blue-400.cursor-pointer
          svg.css-i6dzq1[viewbox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round"]
            rect[x="3" y="3" width="18" height="18" rx="2" ry="2"]
            circle[cx="8.5" cy="8.5" r="1.5"]
            polyline[points="21 15 16 10 5 21"]
        span.flex.items-center.transition.ease-out.duration-300.hover:bg-blue-500.hover:text-white.bg-blue-100.w-8.h-8.px-2.rounded-full.text-blue-400.cursor-pointer
          svg.css-i6dzq1[viewbox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round"]
            path[d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"]
            circle[cx="12" cy="10" r="3"]
        span.flex.items-center.transition.ease-out.duration-300.hover:bg-blue-500.hover:text-white.bg-blue-100.w-8.h-8.px-2.rounded-full.text-blue-400.cursor-pointer
          svg.css-i6dzq1[viewbox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round"]
            polyline[points="4 17 10 11 4 5"]
            line[x1="12" y1="19" x2="20" y2="19"]
      button.flex.items-center.py-2.px-4.rounded-lg.text-sm.bg-blue-600.text-white.shadow-lg
        | Send
        svg.ml-1[viewbox="0 0 24 24" width="16" height="16" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round"]
          line[x1="22" y1="2" x2="11" y2="13"]
          polygon[points="22 2 15 22 11 13 2 9 22 2"]

app/views/posts/_post.html.slim
div id="#{dom_id post}"

.feeds
  .feed-wrapper.mb-4
    .feed-item.border.border-gray-400.rounded.bg-white
      .header.border-b.p-4.flex.justify-between.items-center
        .left.flex.flex-row.items-center
          .user-img.h-10.w-10.border.rounded-full.overflow-hidden.mr-4
            - if post.user.avatar.attached?
              == image_tag post.user.avatar,class: "_6q-tv"
          .user-name-and-place.flex.flex-col
            span.text-sm.font-bold
              =post.user.name

        .right
          svg._8-yf5[aria-label="More options" fill="#262626" height="16" viewbox="0 0 48 48" width="16"]
            circle[clip-rule="evenodd" cx="8" cy="24" fill-rule="evenodd" r="4.5"]
            circle[clip-rule="evenodd" cx="24" cy="24" fill-rule="evenodd" r="4.5"]
            circle[clip-rule="evenodd" cx="40" cy="24" fill-rule="evenodd" r="4.5"]
      .feed-img
        - if post.image.attached?
          == image_tag post.image

      .card-footer.p-4
        .top
          .icons.flex.flex-row.justify-between.items-center
            .left.flex.flex-row
              .like.mr-4
                svg._8-yf5[aria-label="Like" fill="#262626" height="24" viewbox="0 0 48 48" width="24"]
                  path[d="M34.6 6.1c5.7 0 10.4 5.2 10.4 11.5 0 6.8-5.9 11-11.5 16S25 41.3 24 41.9c-1.1-.7-4.7-4-9.5-8.3-5.7-5-11.5-9.2-11.5-16C3 11.3 7.7 6.1 13.4 6.1c4.2 0 6.5 2 8.1 4.3 1.9 2.6 2.2 3.9 2.5 3.9.3 0 .6-1.3 2.5-3.9 1.6-2.3 3.9-4.3 8.1-4.3m0-3c-4.5 0-7.9 1.8-10.6 5.6-2.7-3.7-6.1-5.5-10.6-5.5C6 3.1 0 9.6 0 17.6c0 7.3 5.4 12 10.6 16.5.6.5 1.3 1.1 1.9 1.7l2.3 2c4.4 3.9 6.6 5.9 7.6 6.5.5.3 1.1.5 1.6.5.6 0 1.1-.2 1.6-.5 1-.6 2.8-2.2 7.8-6.8l2-1.8c.7-.6 1.3-1.2 2-1.7C42.7 29.6 48 25 48 17.6c0-8-6-14.5-13.4-14.5z"]

              =form_with url:"/likes", method: :post do |form|
                =form.hidden_field :likeable_type, value: "Post"
                =form.hidden_field :likeable_id, value: "#{post.id}"
                =form.submit value="likes"

              .comment.mr-4
                svg._8-yf5[aria-label="Comment" fill="#262626" height="24" viewbox="0 0 48 48" width="24"]
                  path[clip-rule="evenodd" d="M47.5 46.1l-2.8-11c1.8-3.3 2.8-7.1 2.8-11.1C47.5 11 37 .5 24 .5S.5 11 .5 24 11 47.5 24 47.5c4 0 7.8-1 11.1-2.8l11 2.8c.8.2 1.6-.6 1.4-1.4zm-3-22.1c0 4-1 7-2.6 10-.2.4-.3.9-.2 1.4l2.1 8.4-8.3-2.1c-.5-.1-1-.1-1.4.2-1.8 1-5.2 2.6-10 2.6-11.4 0-20.6-9.2-20.6-20.5S12.7 3.5 24 3.5 44.5 12.7 44.5 24z" fill-rule="evenodd"]
              .share
                svg._8-yf5[aria-label="Share Post" fill="#262626" height="24" viewbox="0 0 48 48" width="24"]
                  path[d="M47.8 3.8c-.3-.5-.8-.8-1.3-.8h-45C.9 3.1.3 3.5.1 4S0 5.2.4 5.7l15.9 15.6 5.5 22.6c.1.6.6 1 1.2 1.1h.2c.5 0 1-.3 1.3-.7l23.2-39c.4-.4.4-1 .1-1.5zM5.2 6.1h35.5L18 18.7 5.2 6.1zm18.7 33.6l-4.4-18.4L42.4 8.6 23.9 39.7z"]
            .right
              .save
                svg._8-yf5[aria-label="Save" fill="#262626" height="24" viewbox="0 0 48 48" width="24"]
                  path[d="M43.5 48c-.4 0-.8-.2-1.1-.4L24 29 5.6 47.6c-.4.4-1.1.6-1.6.3-.6-.2-1-.8-1-1.4v-45C3 .7 3.7 0 4.5 0h39c.8 0 1.5.7 1.5 1.5v45c0 .6-.4 1.2-.9 1.4-.2.1-.4.1-.6.1zM24 26c.8 0 1.6.3 2.2.9l15.8 16V3H6v39.9l15.8-16c.6-.6 1.4-.9 2.2-.9z"]
          .likes.mt-1
            span.font-bold.text-sm
              |  122,780 likes
          .caption.text-sm.mt-3
            b
              =post.body
          .post-date.mt-1
            span.text-xs.text-gray-900
              |  1 minute ago
        .bottom.border-t.pt-3.mt-3
          .wrapper.flex
            =form_with model: [post, post.comments.build], class: "text-sm h-10 w-full outline-none focus:outline-none w-10/12 wrapper flex" do |form|
              =form.text_field :body, class: "text-sm h-10 w-full outline-none focus:outline-none w-12/12", placeholder: "add comment"
              =form.submit "post", class: "text-blue-500 opacity-75 w-2/12 text-right font-bold"

app/views/posts/_provitional.html.slim
.feeds
  .feed-wrapper.mb-4
    .feed-item.border.border-gray-400.rounded.bg-white
      .header.border-b.p-4.flex.justify-between.items-center
        .left.flex.flex-row.items-center
          .user-img.h-10.w-10.border.rounded-full.overflow-hidden.mr-4
            img._6q-tv[alt="nike's profile picture" data-testid="user-avatar" draggable="false" src="https://scontent-nrt1-1.cdninstagram.com/v/t51.2885-19/s150x150/20635165_1942203892713915_5464937638928580608_a.jpg?_nc_ht=scontent-nrt1-1.cdninstagram.com&amp;_nc_ohc=JK-0WwYKXBgAX-mFP6I&amp;oh=e0d86b1c4be3cea94e341f18e17905b3&amp;oe=5F94C764"]
          .user-name-and-place.flex.flex-col
            span.text-sm.font-bold
              | apple
            span.text-xs.font-light.text-gray-900
              | Chiapas, Mexico
        .right
          svg._8-yf5[aria-label="More options" fill="#262626" height="16" viewbox="0 0 48 48" width="16"]
            circle[clip-rule="evenodd" cx="8" cy="24" fill-rule="evenodd" r="4.5"]
            circle[clip-rule="evenodd" cx="24" cy="24" fill-rule="evenodd" r="4.5"]
            circle[clip-rule="evenodd" cx="40" cy="24" fill-rule="evenodd" r="4.5"]
      .feed-img
        img[src="https://images.unsplash.com/photo-1512054502232-10a0a035d672?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=800&amp;q=80" alt=""]
      .card-footer.p-4
        .top
          .icons.flex.flex-row.justify-between.items-center
            .left.flex.flex-row
              .like.mr-4
                svg._8-yf5[aria-label="Like" fill="#262626" height="24" viewbox="0 0 48 48" width="24"]
                  path[d="M34.6 6.1c5.7 0 10.4 5.2 10.4 11.5 0 6.8-5.9 11-11.5 16S25 41.3 24 41.9c-1.1-.7-4.7-4-9.5-8.3-5.7-5-11.5-9.2-11.5-16C3 11.3 7.7 6.1 13.4 6.1c4.2 0 6.5 2 8.1 4.3 1.9 2.6 2.2 3.9 2.5 3.9.3 0 .6-1.3 2.5-3.9 1.6-2.3 3.9-4.3 8.1-4.3m0-3c-4.5 0-7.9 1.8-10.6 5.6-2.7-3.7-6.1-5.5-10.6-5.5C6 3.1 0 9.6 0 17.6c0 7.3 5.4 12 10.6 16.5.6.5 1.3 1.1 1.9 1.7l2.3 2c4.4 3.9 6.6 5.9 7.6 6.5.5.3 1.1.5 1.6.5.6 0 1.1-.2 1.6-.5 1-.6 2.8-2.2 7.8-6.8l2-1.8c.7-.6 1.3-1.2 2-1.7C42.7 29.6 48 25 48 17.6c0-8-6-14.5-13.4-14.5z"]
              .comment.mr-4
                svg._8-yf5[aria-label="Comment" fill="#262626" height="24" viewbox="0 0 48 48" width="24"]
                  path[clip-rule="evenodd" d="M47.5 46.1l-2.8-11c1.8-3.3 2.8-7.1 2.8-11.1C47.5 11 37 .5 24 .5S.5 11 .5 24 11 47.5 24 47.5c4 0 7.8-1 11.1-2.8l11 2.8c.8.2 1.6-.6 1.4-1.4zm-3-22.1c0 4-1 7-2.6 10-.2.4-.3.9-.2 1.4l2.1 8.4-8.3-2.1c-.5-.1-1-.1-1.4.2-1.8 1-5.2 2.6-10 2.6-11.4 0-20.6-9.2-20.6-20.5S12.7 3.5 24 3.5 44.5 12.7 44.5 24z" fill-rule="evenodd"]
              .share
                svg._8-yf5[aria-label="Share Post" fill="#262626" height="24" viewbox="0 0 48 48" width="24"]
                  path[d="M47.8 3.8c-.3-.5-.8-.8-1.3-.8h-45C.9 3.1.3 3.5.1 4S0 5.2.4 5.7l15.9 15.6 5.5 22.6c.1.6.6 1 1.2 1.1h.2c.5 0 1-.3 1.3-.7l23.2-39c.4-.4.4-1 .1-1.5zM5.2 6.1h35.5L18 18.7 5.2 6.1zm18.7 33.6l-4.4-18.4L42.4 8.6 23.9 39.7z"]
            .right
              .save
                svg._8-yf5[aria-label="Save" fill="#262626" height="24" viewbox="0 0 48 48" width="24"]
                  path[d="M43.5 48c-.4 0-.8-.2-1.1-.4L24 29 5.6 47.6c-.4.4-1.1.6-1.6.3-.6-.2-1-.8-1-1.4v-45C3 .7 3.7 0 4.5 0h39c.8 0 1.5.7 1.5 1.5v45c0 .6-.4 1.2-.9 1.4-.2.1-.4.1-.6.1zM24 26c.8 0 1.6.3 2.2.9l15.8 16V3H6v39.9l15.8-16c.6-.6 1.4-.9 2.2-.9z"]
          .likes.mt-1
            span.font-bold.text-sm
              |  122,780 likes
          .caption.text-sm.mt-3
            b
              | apple
            |  new Iphone release ✨
          .post-date.mt-1
            span.text-xs.text-gray-900
              |  1 minute ago
        .bottom.border-t.pt-3.mt-3
          .wrapper.flex
            input.text-sm.h-10.w-full.outline-none.focus:outline-none.w-10/12[type="text" placeholder="Add a comment"]
            button.text-blue-500.opacity-75.w-2/12.text-right.font-bold
              | post

app/views/posts/edit.html.slim
h1 Editing post

== render "form", post: @post

br

div
  => link_to "Show this post", @post
  '|
  =< link_to "Back to posts", posts_path

app/views/posts/index.html.slim
p style="color: green" = notice

#posts

.page-content.pt-6.h-full
  .container.mx-auto.flex.h-full
    .left.pr-4 class="w-8/12"

      .feeds
        .feed-wrapper.mb-

          - @posts.each do |post|
            == render post


    .right.h-screen.overflow-visible.h-full class="w-4/12"
      .first.fixed.pl-4.w-full style=("top:85px;  max-width: 293px;")
        .profile.flex.items-center.p-3.mb-4
          .avatar.rounded-full.overflow-hidden.mr-3
            img alt="" height="56px" src="https://scontent-ort2-1.cdninstagram.com/v/t51.2885-19/44884218_345707102882519_2446069589734326272_n.jpg?_nc_ht=scontent-ort2-1.cdninstagram.com&_nc_ohc=RLYRR3IenIMAX_WuH3u&oh=f63257aee4bcbf147d7a26c7da5b3467&oe=5F96310F" width="56px" /
          .user-name
            span.text-lg.font-semibold.text-gray-700 u__graphics
            span.text-sm.text-gray-600.block Ugraphics
        .suggestion-users
          .title.flex.w-full.justify-between.text-sm
            .left
              h1.font-bold Suggestions For You
            .right
              span See All
          .users-wrapper.mt-4.flex.w-full.justify-between.items-center
            .user-item.flex.flex-row.pl-2
              .user-img.h-10.w-10.border.rounded-full.overflow-hidden.mr-4
                img alt=("realdonaldtrump's profile picture") src="https://scontent-nrt1-1.cdninstagram.com/v/t51.2885-19/s150x150/23823676_515039535523575_7479748231031685120_n.jpg?_nc_ht=scontent-nrt1-1.cdninstagram.com&_nc_ohc=zLTqJ5i4bawAX9aEwSk&oh=3bd3cf886021fc3ad74a9258163f319b&oe=5F93487B" /
              .user-name.flex.flex-col
                span.text-sm.font-semibold realdonaldtrump
                span.text-xs.-mt-1.text-gray-700 populer
            a.follow.text-blue-600.text-sm.font-semibold href=""  follow
          .users-wrapper.mt-4.flex.w-full.justify-between.items-center
            .user-item.flex.flex-row.pl-2
              .user-img.h-10.w-10.border.rounded-full.overflow-hidden.mr-4
                img._6q-tv alt=("shinzoabe's profile picture") data-testid="user-avatar" draggable="false" src="https://scontent-nrt1-1.cdninstagram.com/v/t51.2885-19/s150x150/28765771_2034399086813186_5509661386784899072_n.jpg?_nc_ht=scontent-nrt1-1.cdninstagram.com&_nc_ohc=qheOj6mJM98AX83my9F&oh=8a8985205ad5a19ae0905a3c3a77906b&oe=5F93F87C" /
              .user-name.flex.flex-col
                span.text-sm.font-semibold shinzoabe
                span.text-xs.-mt-1.text-gray-700 populer
            a.follow.text-blue-600.text-sm.font-semibold href=""  follow
          .users-wrapper.mt-4.flex.w-full.justify-between.items-center
            .user-item.flex.flex-row.pl-2
              .user-img.h-10.w-10.border.rounded-full.overflow-hidden.mr-4
                img._6q-tv alt=("nike's profile picture") data-testid="user-avatar" draggable="false" src="https://scontent-nrt1-1.cdninstagram.com/v/t51.2885-19/s150x150/26155970_1584552474997482_4541081815552622592_n.jpg?_nc_ht=scontent-nrt1-1.cdninstagram.com&_nc_ohc=f5mhOmP7WT0AX9kw3Eh&oh=fd2a3ba71bee8608cda04d04196746b8&oe=5F94C3CE" /
              .user-name.flex.flex-col
                span.text-sm.font-semibold nike
                span.text-xs.-mt-1.text-gray-700 populer
            a.follow.text-blue-600.text-sm.font-semibold href=""  follow

app/views/posts/new.html.slim
h1 New post

== render "form", post: @post

br

div
  = link_to "Back to posts", posts_path

app/views/posts/show.html.slim
p style="color: green" = notice

== render @post

div
  => link_to "Edit this post", edit_post_path(@post)
  '|
  =< link_to "Back to posts", posts_path

  = button_to "Destroy this post", @post, method: :delete